### ISSUE TITLE
Install fails with JSON::Validator >= 3.00

### ISSUE THREAD

**Issue by rabbiveesh** [mohawk2/SQL-Translator-Parser-OpenAPI#2]
In newer versions of JSON::Validator, the module `JSON::Validator::OpenAPI` has been moved to `JSON::Validator::OpenAPI::Mojolicious` (I'm actually not sure if that's the same thing). This breaks this module, seeing as the former is a dependency.

I would very much like to use this module, so if you could look into this, it would be great.

**Comment by mohawk2** [comment]
Thanks for the report!

I have fixed this just by switching the module used to `JSON::Validator::OpenAPI::Mojolicious`. Now the tests all pass again, and I have released the new version as 0.06. Let me know of any problems that arise!

**Comment by mohawk2** [comment]
Caused by https://github.com/mojolicious/json-validator/issues/145
